### ISSUE TITLE
Use BrowserRouter

### ISSUE THREAD

**Issue by Noitidart** [1yzo/kharcha#1]
https://github.com/1yzo/kharcha/blob/2f2be9ec998868ba79ac76483460bbea84868baf/src/routers/AppRouter.js#L15

No need to use `<Router history={history}>`, cuz history is another package. Just take `<BrowserRouter>`

**Comment by 1yzo** [comment]
I have to use my own history cuz i have to push to the dashboard page from outside <AppRouter/ >

**Comment by Noitidart** [comment]
Show me where you do that, I'll show you alternative.
